# Homework 7


**Concepts covered:**

numpy arrays, array element access, basic descriptive statistics, initializing arrays, numpy functions and methods.  


**Instructions:**

Be sure to run each code block after you edit it to make sure it runs as expected. When you are done, we strongly recommend you run all the code from scratch (Runtime menu -> Restart and Run all) to make sure your current code works for all problems.

If your code raises an exception when run from scratch, it will interfere with the auto-grader process causing you to lose some or all points for this homework. Please ask for help on Piazza, attend office hours or schedule an appointment with your learning facilitator if you get stuck.


**Warning against using generative AI:**

We recommend *in the strongest terms* against using generative AI in solving any homework assignment in this module. The goal of these assignments is for you to learn the fundamental concepts about programming: syntax, correctness, problem decomposition, and skepticism. While we know that generative AI can solve all of these problems, you will not be learning anything and will get confused as this module progresses.

While we encourage you to use AI to generate practice problems, you should try to solve these problems with the help of the sample problems, and examples on blackboard and experimentation.

**Sample Output:**

For each problem description, a sample output has been included to show what the expected output should be.


**Docstrings and Comments:**

Include a *documentation string* (docstring) for each function definition, as well as comments in the body of your code to explain each control structures (e.g., decision, loop), function call, or formula.

**Review Problem 1**

**Concept:** *List data type, list comprehension.*

**Task:**

Write a function `stdev(values)` that takes a 1D Python list of numbers and returns the population standard deviation.

**Sample Output:**


```
stdev([1, 2, 3]) should return approximately 0.8164965809

stdev([5, 5, 5, 5]) should return 0.0
```


In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE



In [ ]:
# TO DO: WRITE YOUR TEST CASES HERE
stdev([3, 5, 9])

**Review Problem 2**

**Concept:** *List element access.*

**Task:**

Write a function `sum_list(a, b)` that takes two same-length 1D lists and returns a new list containing the element-wise sums.

If the lengths differ, print a message indicating incompatible lengths in this format: Incompatible lengths: {len(a)} vs {len(b)}.
Use list comprehension for this, not numpy.

**Sample Output:**

```
sum_list([2, 4, 6], [1, 3, 5]) → [3, 7, 11]
```


In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE



Test cases for problem 2

In [ ]:
# TO DO: WRITE YOUR TEST CASES HERE



The following starter code will be used in several problems. Run the following cell before continuing.

In [ ]:
# STARTER CODE TO DEFINE SOME NUMPY ARRAYS:
import numpy as np

a = np.arange(12)
b = np.array([i * 2 for i in range(1,13)])
c = np.random.randint(0, 10, 12)
print(f'a = {a}')
print(f'b = {b}')
print(f'c = {c}')



a = [ 0  1  2  3  4  5  6  7  8  9 10 11]
b = [ 2  4  6  8 10 12 14 16 18 20 22 24]
c = [9 2 4 5 5 2 1 3 8 6 0 7]


**Problem 3**

**Concept:** *Array operations.*

**Task:**

Using the arrays a, b, c defined in the starter code:

a.   Compute sum of arrays `a` plus `b`, and store the result in the variable `x`.

b.   Compute the product of arrays `a` and `b`, and store the result in the variable `y`.

c.   Compute the dot product of arrays `a` and `b`, and store the result in the variable `z`.

d.   Re-shape the array `x` as a 2x6 array, and store the result in the variable `q`.

e.   Re-shape the array `y` as a 6x2 array, and store the result in the variable `r`.

f.   Compute the dot product of arrays `q` and `r`, and store the result in the varaible `s`.

Print `x`, `y`, `z`, `q`, `r`, `s` as you go to check your work.

**Sample Output:**

```
x = [ 3  7 11 15 19 23 27 31 35 39 43 47]
y = [  0   6  18  36  60  90 126 168 216 270 330 396]
z = 2184

q =
[[ 3  7 11 15 19 23]
 [27 31 35 39 43 47]]

r =
[[  0   6]
 [ 18  36]
 [ 60  90]
 [126 168]
 [216 270]
 [330 396]]

s =
[[15660 20484]
 [37476 49020]]

```


In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE



**Problem 4**

**Concept:** *Array operations, iteration with loop, numpy functions and methods.*

**Task:**

Write a function `mean_rowwise(x)` that takes a 2D numpy array and returns a 2D column vector containing the mean of each row.

**Numeric Example:**

If `x = [[1,2,3],[10,0,-10]]`, the row means are `[[2.],[0.]]`.


**Example Function Call:**

```
mean_rowwise(np.array([[0.2, 0.3, 0.4]])) returns [[0.3]]
```




In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE



Test cases for problem 4

In [ ]:
# TO DO: WRITE YOUR TEST CASES HERE



**Problem 5**

**Concept:** *Array operations, iteration with loop, boolean values, numpy functions and methods.*

**Task:**

Write a function `check_row_sum(x)` that returns `True` if every row in a 2D numpy array sums to 1.0 (tolerance: between `0.999` and `1.001`), otherwise return `False`.

**Example Function Calls:**

`check_row_sum([[0.2,0.8],[0.5,0.5]])` returns `True`

`check_row_sum([[0.0, 1.0], [0.9999, 0.0012]])` returns `False`
```



In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE



Test cases for problem 5

In [ ]:
# TO DO: WRITE YOUR TEST CASES HERE




**Problem 6**

**Concept:** *Array operations, numpy functions and methods.*

**Task:**

Write a function `softmax(z)` that takes in a 1D numpy array of values $z_i$, and returns an array composed of $\frac{e^{z_i}}{\sum e^{z_i}}$.

The output array shape should be the same as the input array shape.

This formula is the [softmax](https://en.wikipedia.org/wiki/Softmax_function) formula used to adjust raw machine learning outputs into more suitable probability estimates.

**Example Function Calls:**

`softmax(np.array([0,0]))` returns `np.array([0.5, 0.5])`

`softmax(np.array([-1, 0, 1]))` returns `np.array([0.09003057 0.24472847 0.66524096])`


In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE



Test cases for problem 6

In [ ]:
# TO DO: WRITE YOUR TEST CASES HERE




**Problem 7**

**Concept:** *Array operations.*

**Task:**
Write `softmax_2d(z)` that applies softmax row-by-row to a 2D numpy array, returning an array of the same shape.

**Example Function Calls:**

`softmax_2d(np.array([[0,0],[1,1]]))` returns `np.array([[0.5,0.5],[0.5,0.5]])`


In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE



Test cases for problem 7

In [ ]:
# TO DO: WRITE YOUR TEST CASES HERE




**Problem 8**

**Concept:** *Descriptive statistics, row-wise operations, numpy functions and methods.*

**Task:**

Write `three_stats(x)` that takes an `n x k` array and returns an 3 by N array of:

1. row minimums

2. row medians

3. row maximums


**Hint:**
You can use np.min, np.median, np.max

**Example Function Calls:**

`three_stats(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]]))`
returns
`np.array([[1. 4. 7.], [2. 5. 8.], [3. 6. 9.]])`



In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE



Test cases for problem 8

In [ ]:
# TO DO: WRITE YOUR TEST CASES HERE


**Problem 9**

**Concept:** *Row-wise operations, numpy functions and methods.*

**Task:**
Write `max_row_sum(a)` that takes a 2D numpy array and returns the largest row sum.

**Numeric Example:**

```[[1,2],[10,-1],[0,0]] row sums [3,9,0] → returns 9```

**Example Function Call:**

`max_row_sum(np.array([[1, 2, 3], [9, 9, 9], [1000, 100, 900]]))` returns `2000`




In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE



Test cases for problem 9

In [ ]:
# TO DO: WRITE YOUR TEST CASES HERE


**Problem 10**

**Concept:** *Array operations; thinking about dimensions and element access.*

**Task:**

Write the function `array_init_parameters(a)` that returns either:

*  if all elements are the same and the array `a` can be recreated using `np.full((w, h), v)`, return the tuple `(w, h, v)` corresponding to (width, height, value)

* otherwise return `None`

**Numeric Example:**

```[[7,7],[7,7]] → (2,2,7)```

```[[7,7],[7,8]] → None```



In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE



Test cases for problem 10

In [ ]:
# TEST CASES TO TRY:

# array_init_parameters(np.array([[0]]))

# array_init_parameters(np.array([[0, 1]]))


# array_init_parameters(np.array([[3], [3]]))

# array_init_parameters(np.array([[4, 4, 4], [4, 4, 4], [4, 4, 4], [4, 4, 4]]))


**Problem 11**

**Concept:** *Array operations; thinking about dimensions and element access.*

**Task:**

[Kakuro](https://en.wikipedia.org/wiki/Kakuro) is a logic puzzle where the goal is to fill in numbers so that the rows and columns add up to specified numbers.

Write `kakuro_test(a, row_sums, column_sums)` that returns `True` if:

* each row sum matches `row_sums`

* each column sum matches `column_sums`

* Otherwise return `False`.

**Numeric Example:**

For the input
`kakuro_test(np.array([[7, 2], [3, 4]]), [9, 7], [10, 6])`

The row sums are 7+2=9 and 3+4=7, which matches the third element `[9, 7]`

The column sums are 7+3=10 and 2+4=6, which matches the fourth element `[10, 6]`

So this should return `True`



In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE



Test cases for problem 11

In [ ]:
# TEST CASES TO TRYU

# this should return True
p11_test_1_result = kakuro_test(np.array([[0, 1, 2], [3, 4, 5]]), [3, 12], [3, 5, 7])
print(f'p11_test_1_result = {p11_test_1_result}')

# this should return False
p11_test_2_result = kakuro_test(np.array([[0, 2, 4], [3, 4, 5]]), [3, 12], [3, 5, 7])
print(f'p11_test_2_result = {p11_test_2_result}')



**Problem 12**

**Concept:** *File reading, parsing data values, array creation.*

**Task:**
Write the function `read_csv_to_array(filename)` that reads a CSV file, discards the header row, converts each element to a floating-point number, and returns a 2D numpy array.

**Sample Output:**

If file contains:

```
foo,bar
2,4
6,8
```

The function should return:
```
np.array([[2. 4.][6. 8.]])
```

In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE



Test cases for problem 12

In [7]:
# TEST CASES HERE
data = read_csv_to_array("data1.csv")
print(data)


[[ 22. 183.  51.]
 [ 62. 168.  57.]
 [ 42. 150.  98.]
 [ 49. 163.  90.]
 [ 49. 129.  98.]
 [ 60. 171.  90.]
 [ 59. 181.  65.]
 [ 62. 136.  83.]
 [ 18. 144.  67.]
 [ 64. 189.  73.]]


**Problem 13**

**Concept:** *File reading, parsing data values, array creation.*


**Task:**

Write the function `get_column_stats(filename)` that a CSV file, discards the header row, and returns a 2D numpy array where the rows contain in order: the means, standard deviations, minimums, and maximums, of each column.

**Sample Output:**

If file contains:
```
a,b,c
1,2,3
4,5,6
```
The resulting columns means are

```np.array([[2.5, 3.5, 4.5], [1.5, 1.5, 1.5], [1, 2, 3], [4, 5, 6]])```


In [ ]:
# TO DO: WRITE YOUR SOLUTION HERE



Test cases for problem 13

In [ ]:
# TEST CASES HERE
stats = get_column_stats("data1.csv")
print(stats)
